[workspace]
members = [
  "metabonding",
  "metabonding/meta",
]


[patch.crates-io]
elrond-wasm-debug = { git = "https://github.com/multiversx/mx-sdk-rs", package = "elrond-wasm-debug", branch = "reproducible/v0.36.1" }
