// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    growth_program
    (
        init => init
        upgrade => upgrade
        addProject => add_project
        setProjectOwner => set_project_owner
        setMinRewardsPeriod => set_min_rewards_period
        setMinWeeklyRewardsValue => set_min_weekly_rewards_value
        depositInitialRewards => deposit_initial_rewards
        depositAdditionalRewards => deposit_additional_rewards
        ownerWithdrawRewards => owner_withdraw_rewards
        finishProgram => finish_program
        updateRewards => update_rewards_endpoint
        changeSigner => change_signer
        getCurrentWeek => get_current_week
        getFirstWeekStartEpoch => first_week_start_epoch
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
