// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    metabonding
    (
        changeSigner
        pause
        unpause
        isPaused
        addProject
        removeProject
        clearExpiredProjects
        getAllProjectIds
        getProjectById
        getCurrentWeek
        addRewardsCheckpoint
        depositRewards
        getRewardsForWeek
        claimRewards
        getUserClaimableWeeks
        addSCAddressToWhitelist
        removeSCAddressFromWhitelist
        isSCAddressWhitelisted
    )
}

elrond_wasm_node::wasm_empty_callback! {}
